### ISSUE TITLE
Check usage of Visual Studio Code naming adheres to brand guideline of MS

### ISSUE THREAD

**Issue by bs-jokri** [software-engineering-project-org/vscode-plugin-automotive-app-deployment#132]
### Question

https://code.visualstudio.com/brand

it seems to be ok to use the logo. However, the naming of the app needs probably be adjusted. Eg we name it VSCode Leda App deployer but MS wants to use it like Leda App Deployer for Visual Studio Code

> Do you make content (extensions, training material, etc) for Visual Studio Code?
> If so, please use the following format when naming your content if you want to refer that it is optimized for, related to, or works with Visual Studio Code:
> 
> OK
> Correct: [My Extension Name] for Visual Studio Code
> 
> Not OK
> Incorrect: Visual Studio Code [My Extension Name]

**Comment by dangelic** [comment]
Changed "VSCode" in documentation/naming to "Visual Studio Code", e.g. in "...Extension for Visual Studio Code". 

Note:  "vscode" in our source code itself remains vscode, as it refers to the node-module vscode.
