### ISSUE TITLE
Remove /welcomePage.html if it is not used but the Readme.md

### ISSUE THREAD

**Issue by bs-jokri** [software-engineering-project-org/vscode-plugin-automotive-app-deployment#133]
### Severity

None

### Current Behavior

You still have the file
https://github.com/software-engineering-project-org/vscode-plugin-automotive-app-deployment/blob/main/resources/welcomePage.html

in the code. I understood, that you render the welcome page from the readme file. Which file is correct? Remove https://github.com/software-engineering-project-org/vscode-plugin-automotive-app-deployment/blob/main/resources/welcomePage.html
if it is not used anymore.

### Code of Conduct

- [ ] I agree to follow this project's "Code of Conduct".

**Comment by dangelic** [comment]
This behavior is intended. The README.md contains more points than the welcome page html (e.g. installation steps of the plugin). The welcome page html is displayed INSIDE the plugin when a user first runs it. Furthermore, the welcome page can be displayed manually via info button and serves as a "helping manual" inside the plugin when needed. 
-> Points like the installation steps make no sense here, as the plugin is already installed if the user sees the welcome page.

**Comment by dangelic** [comment]
@martinh-dev We might consider to rename this page to "manual" or something else to be more convenient.

**Comment by dangelic** [comment]
NOTE: I've changed the naming here. Welcome Page is now named "User Manual" for more convenience.
