### ISSUE TITLE
[Q]: What does the test.tar file contain? Is it copyrighted material?

### ISSUE THREAD

**Issue by bs-jokri** [software-engineering-project-org/vscode-plugin-automotive-app-deployment#134]
### Question

What does 
https://github.com/software-engineering-project-org/vscode-plugin-automotive-app-deployment/blob/main/resources/test.tar
contain? is this a a test container? If so, what code does it contain? Probably GPL or otherwise copyrighted binaries (bash, etc). If this is the case, we need to remove this file

**Comment by dangelic** [comment]
@cpotter302 Please check and remove if necessary.

**Comment by cpotter302** [comment]
The file test.tar was just used for testing purposes and is now obsolete. Done by deleting
