### ISSUE TITLE
Function doesn't sound like generic helper function but specific for the welcome page. Probably move to separate package?

### ISSUE THREAD

**Issue by bs-jokri** [software-engineering-project-org/vscode-plugin-automotive-app-deployment#135]
https://github.com/software-engineering-project-org/vscode-plugin-automotive-app-deployment/blob/46335cb73685064d00ad020b7bae3b9a88975846/src/helpers/helpers.ts#L51

**Comment by dangelic** [comment]
Oursource the openUserManual (formerly openWelcomePage) function to a separate file. Also, our generic helpers are now in the directory "utils", containing all generic helpers in a single file plus other utility functions like the openUserManual.
