### ISSUE TITLE
Probably we need to think about renaming Stage 1 - 3 to something more understandable

### ISSUE THREAD

**Issue by bs-jokri** [software-engineering-project-org/vscode-plugin-automotive-app-deployment#137]
We called Stage 1 - 3 because we improved the functionality incrementally. However, for an outsider to the project this might not be understandable. So probably we need to rename the three stages. Ideas?

https://github.com/software-engineering-project-org/vscode-plugin-automotive-app-deployment/blob/46335cb73685064d00ad020b7bae3b9a88975846/src/setup/cmdProperties.ts#L19

**Comment by dangelic** [comment]
Renamed STAGES to "Deployment-Variants" (01, 02, 03). This is now consistent throughout the whole code base, referencing classes, methods, references, docs, ...

**Comment by cpotter302** [comment]
corresponding pull request is merged
