### ISSUE TITLE
Figure out why not only Apache 2.0 but different licenses. Fix entry

### ISSUE THREAD

**Issue by bs-jokri** [software-engineering-project-org/vscode-plugin-automotive-app-deployment#139]
https://github.com/software-engineering-project-org/vscode-plugin-automotive-app-deployment/blob/46335cb73685064d00ad020b7bae3b9a88975846/NOTICE-3RD-PARTY-CONTENT.md?plain=1#L22

**Comment by cpotter302** [comment]
Since we did not specify a license in our package.json (which is now fixed) the tool was assuming that we use all available licenses
