### ISSUE TITLE
Why do I need this description? Maybe add a section "Prerequisites to LAD"

### ISSUE THREAD

**Issue by bs-jokri** [software-engineering-project-org/vscode-plugin-automotive-app-deployment#141]
https://github.com/software-engineering-project-org/vscode-plugin-automotive-app-deployment/blob/46335cb73685064d00ad020b7bae3b9a88975846/README.md?plain=1#L192

It seems this section explains what is required to use LAD. Probably it is more helpful if you describe "Prerequisites to LAD" and there you describe what the target device requires (kanto etc)

**Comment by dangelic** [comment]
Changed the description to be more clear. These are (in my understanding) the prerequisites to use the plugin without Kanto as underlying distro. You need this if you maybe want to deploy on raspbian OS or similar.
