### ISSUE TITLE
What is this file good for? Can it be removed or should it be adjusted to be specific to this project

### ISSUE THREAD

**Issue by bs-jokri** [software-engineering-project-org/vscode-plugin-automotive-app-deployment#142]
https://github.com/software-engineering-project-org/vscode-plugin-automotive-app-deployment/blob/46335cb73685064d00ad020b7bae3b9a88975846/vsc-extension-quickstart.md?plain=1#L1

**Comment by dangelic** [comment]
Removed it. I add a link to VSCode plugin development documentation in CONTRIBUTION.md
