### ISSUE TITLE
Copy artifact to Leda

### ISSUE THREAD

**Issue by cpotter302** [software-engineering-project-org/vscode-plugin-automotive-app-deployment#67]
**Description:** As a developer, I want to copy a file to a specific filepath on the Leda device so that I can ensure the file is stored in the correct location for further processing.

**Definition of Done (DoD)**: Programming, Testing, Documentation  
--> Refer to [Confluence](http://google.com) for detailed DoD.

Prerequisites: #66 
Links: #40

**Comment by dangelic** [comment]
@cpotter302 Please refer to: https://linux.die.net/man/1/scp for SCP handling. :-)
